import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster as Toaster2 } from "@/components/ui/toaster";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Toaster } from 'react-hot-toast';
import Background from "@/components/Background";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <div className="min-h-screen h-full max-w-screen 
        overflow-hidden relative 
           mx-auto 
        ">
          <Navbar />
          <div className="h-full  lg:px-20 md:px-10 px-2">
            {children}
          </div>
          <Background />
        </div>
        <Footer />
        <Toaster2 />
        <Toaster />



      </body>
    </html >
  );
}
